engines:
  phpmd:
    enabled: true
    config:
      standard: "PSR1,PSR2"
    checks:
      Controversial/CamelCaseParameterName:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
      Design/LongClass:
        enabled: false
      Design/TooManyMethods:
        enabled: false
      Naming/LongVariable:
        enabled: false

ratings:
  paths:
  - "**.php"

exclude_paths:
- build/*
- examples/*
- vendor/*
- filestack/FilestackConfig.php