language: php

php:
  - 7.3
  - 7.4
  
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v